import { RestaurantProfile, Table, MenuItem, Reservation, AuditEvent } from '../types/restaurant';

export const DEFAULT_TENANT_ID = 'raso-minang-padang-01';

export const initialRestaurantProfile: RestaurantProfile = {
  tenantId: DEFAULT_TENANT_ID,
  name: 'Raso Minang',
  tagline: 'Masakan Padang Autentik & Hangat di Setiap Meja',
  address: 'Jl. Rasa Nusantara No. 8, Kebayoran Baru',
  city: 'Jakarta Selatan',
  phone: '+62 812-3456-7890',
  openingHours: 'Setiap Hari: 10:00 – 22:00 WIB',
  openTime: '10:00',
  closeTime: '22:00',
  description: 'Menyajikan hidangan Minang otentik dengan racikan rempah warisan leluhur. Tersedia area Indoor ber-AC, VIP room privat, dan Outdoor teras yang asri.',
  policies: [
    'Reservasi meja diproses dengan status pending dan menunggu konfirmasi staff.',
    'Batas waktu toleransi kedatangan adalah 15 menit dari jadwal reservasi.',
    'Pembatalan atau perubahan jadwal dapat dilakukan maksimal 1 jam sebelum waktu kedatangan.',
    'Kapasitas maksimum per meja disesuaikan demi kenyamanan bersantap.'
  ]
};

export const initialTables: Table[] = [
  { id: 'tbl-1', number: 'M-01', capacity: 2, area: 'Indoor', status: 'available', tenantId: DEFAULT_TENANT_ID },
  { id: 'tbl-2', number: 'M-02', capacity: 2, area: 'Indoor', status: 'available', tenantId: DEFAULT_TENANT_ID },
  { id: 'tbl-3', number: 'M-03', capacity: 4, area: 'Indoor', status: 'available', tenantId: DEFAULT_TENANT_ID },
  { id: 'tbl-4', number: 'M-04', capacity: 4, area: 'Indoor', status: 'available', tenantId: DEFAULT_TENANT_ID },
  { id: 'tbl-5', number: 'M-05', capacity: 6, area: 'Indoor', status: 'available', tenantId: DEFAULT_TENANT_ID },
  { id: 'tbl-6', number: 'M-06', capacity: 4, area: 'Outdoor', status: 'available', tenantId: DEFAULT_TENANT_ID },
  { id: 'tbl-7', number: 'M-07', capacity: 4, area: 'Outdoor', status: 'available', tenantId: DEFAULT_TENANT_ID },
  { id: 'tbl-8', number: 'M-08', capacity: 6, area: 'Outdoor', status: 'available', tenantId: DEFAULT_TENANT_ID },
  { id: 'tbl-9', number: 'VIP-01', capacity: 8, area: 'VIP', status: 'available', tenantId: DEFAULT_TENANT_ID },
  { id: 'tbl-10', number: 'VIP-02', capacity: 10, area: 'VIP', status: 'available', tenantId: DEFAULT_TENANT_ID },
];

export const initialMenuItems: MenuItem[] = [
  // Lauk Utama
  {
    id: 'menu-1',
    name: 'Rendang Daging Sapi',
    category: 'Lauk Utama',
    price: 35000,
    description: 'Daging sapi pilihan dimasak perlahan 8 jam dengan santan kental dan 16 rempah Minang pilihan.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 2,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-2',
    name: 'Ayam Pop Spesial',
    category: 'Lauk Utama',
    price: 28000,
    description: 'Ayam kampung muda gurih lembut direbus air kelapa, disajikan dengan sambal tomat pop khas Bukittinggi.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 1,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-3',
    name: 'Dendeng Balado Batokok',
    category: 'Lauk Utama',
    price: 38000,
    description: 'Dendeng sapi renyah gurih dipukul pipih dan dilumuri cabai merah ulek kasar minyak kelapa.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 3,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-4',
    name: 'Gulai Tunjang (Kikil)',
    category: 'Lauk Utama',
    price: 36000,
    description: 'Kikil sapi empuk dan kenyal dalam kuah gulai kuning gurih kaya kapulaga dan kunyit.',
    isAvailable: true,
    isPopular: false,
    spicinessLevel: 2,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-5',
    name: 'Gulai Kepala Ikan Kakap',
    category: 'Lauk Utama',
    price: 65000,
    description: 'Kepala kakap merah segar dengan kuah gulai pedas asam beraroma daun ruku-ruku.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 2,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-6',
    name: 'Ayam Bakar Padang',
    category: 'Lauk Utama',
    price: 28000,
    description: 'Ayam berbalut bumbu kuning rempah dibakar harum arang batok kelapa.',
    isAvailable: true,
    isPopular: false,
    spicinessLevel: 2,
    tenantId: DEFAULT_TENANT_ID,
  },

  // Sayur & Kuah
  {
    id: 'menu-7',
    name: 'Sayur Daun Singkong & Nangka',
    category: 'Sayur & Kuah',
    price: 12000,
    description: 'Rebusan daun singkong segar berpadu gulai nangka muda gurih santan sedang.',
    isAvailable: true,
    isPopular: false,
    spicinessLevel: 1,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-8',
    name: 'Gulai Daun Pakis (Paku)',
    category: 'Sayur & Kuah',
    price: 15000,
    description: 'Pucuk paku segar dimasak gulai santan kunyit wangi asam kandis.',
    isAvailable: true,
    isPopular: false,
    spicinessLevel: 1,
    tenantId: DEFAULT_TENANT_ID,
  },

  // Pelengkap & Sambal
  {
    id: 'menu-9',
    name: 'Sambal Ijo Khas Padang',
    category: 'Pelengkap & Sambal',
    price: 8000,
    description: 'Cabai hijau keriting kukus ulek kasar dengan tomat hijau, bawang merah, dan perasan jeruk limau.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 2,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-10',
    name: 'Kerupuk Jangek (Kulit) Kuah Gulai',
    category: 'Pelengkap & Sambal',
    price: 12000,
    description: 'Kerupuk kulit sapi renyah disiram kuah gulai panas gurih.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 1,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-11',
    name: 'Perkedel Kentang Minang',
    category: 'Pelengkap & Sambal',
    price: 9000,
    description: 'Perkedel kentang lembut padat dengan cincangan daging sapi dan seledri.',
    isAvailable: true,
    isPopular: false,
    spicinessLevel: 1,
    tenantId: DEFAULT_TENANT_ID,
  },

  // Minuman
  {
    id: 'menu-12',
    name: 'Teh Talua (Teh Telur)',
    category: 'Minuman',
    price: 18000,
    description: 'Minuman penambah stamina khas Minang: kocokan kuning telur bebek, gula aren, seduhan teh pekat dan jeruk nipis.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 1,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-13',
    name: 'Es Tebak Tradisional',
    category: 'Minuman',
    price: 20000,
    description: 'Es campur Minang dengan olahan tepung beras tebak, cincau hitam, tapai ketan hitam, sirup merah dan santan.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 1,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-14',
    name: 'Es Timun Serut Jeruk Nipis',
    category: 'Minuman',
    price: 15000,
    description: 'Minuman penyegar peredam pedas dari serutan mentimun segar, selasih, gula asli, dan perasan jeruk nipis.',
    isAvailable: true,
    isPopular: false,
    spicinessLevel: 1,
    tenantId: DEFAULT_TENANT_ID,
  },
];

export const initialReservations: Reservation[] = [
  {
    id: 'res-1',
    code: 'RM-1001',
    customerName: 'Ahmad Fauzi',
    customerPhone: '081298765432',
    tableId: 'tbl-3',
    tableNumber: 'M-03',
    tableArea: 'Indoor',
    date: '2026-08-22',
    time: '12:30',
    guestCount: 4,
    status: 'seated',
    autoConfirmed: true,
    qrToken: 'QR-RM-1001-VERIFIED',
    seatedAt: '2026-08-22T12:28:00Z',
    paymentStatus: 'settlement',
    paymentAmount: 50000,
    paymentMethod: 'gopay',
    notes: 'Mohon siapkan sambal ijo porsi ekstra.',
    tenantId: DEFAULT_TENANT_ID,
    createdAt: '2026-08-22T10:20:00Z',
    updatedAt: '2026-08-22T12:28:00Z',
  },
  {
    id: 'res-2',
    code: 'RM-1002',
    customerName: 'Siti Rahmawati',
    customerPhone: '081388776655',
    tableId: 'tbl-9',
    tableNumber: 'VIP-01',
    tableArea: 'VIP',
    date: '2026-08-22',
    time: '19:00',
    guestCount: 8,
    status: 'confirmed',
    autoConfirmed: true,
    qrToken: 'QR-RM-1002-VERIFIED',
    paymentStatus: 'settlement',
    paymentAmount: 100000,
    paymentMethod: 'qris',
    notes: 'Makan malam keluarga besar perayaan ulang tahun.',
    tenantId: DEFAULT_TENANT_ID,
    createdAt: '2026-08-22T08:15:00Z',
    updatedAt: '2026-08-22T08:16:00Z',
  },
  {
    id: 'res-3',
    code: 'RM-1003',
    customerName: 'Budi Santoso',
    customerPhone: '085612349876',
    tableId: 'tbl-6',
    tableNumber: 'M-06',
    tableArea: 'Outdoor',
    date: '2026-08-22',
    time: '13:00',
    guestCount: 2,
    status: 'confirmed',
    autoConfirmed: true,
    qrToken: 'QR-RM-1003-VERIFIED',
    paymentStatus: 'unpaid',
    paymentAmount: 25000,
    notes: 'Area bebas asap rokok jika memungkinkan.',
    tenantId: DEFAULT_TENANT_ID,
    createdAt: '2026-08-22T09:00:00Z',
    updatedAt: '2026-08-22T09:00:00Z',
  },
  {
    id: 'res-4',
    code: 'RM-1004',
    customerName: 'Dewi Lestari',
    customerPhone: '081700112233',
    tableId: 'tbl-1',
    tableNumber: 'M-01',
    tableArea: 'Indoor',
    date: '2026-08-22',
    time: '11:00',
    guestCount: 2,
    status: 'completed',
    autoConfirmed: true,
    qrToken: 'QR-RM-1004-VERIFIED',
    seatedAt: '2026-08-22T11:02:00Z',
    completedAt: '2026-08-22T12:15:00Z',
    paymentStatus: 'settlement',
    paymentAmount: 25000,
    paymentMethod: 'bca_va',
    tenantId: DEFAULT_TENANT_ID,
    createdAt: '2026-08-22T07:00:00Z',
    updatedAt: '2026-08-22T12:15:00Z',
  },
];

export const initialAuditEvents: AuditEvent[] = [
  {
    id: 'aud-1',
    actor: 'Staf Penerima Tamu',
    action: 'GUEST_CHECKIN_SEATED',
    entity: 'Reservasi RM-1001',
    timestamp: '2026-08-22T12:28:00Z',
    details: 'Tamu Ahmad Fauzi tiba di restoran. Meja M-03 diubah ke status TERISI (Seated).',
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'aud-2',
    actor: 'Sistem Reservasi Otomatis',
    action: 'AUTO_CONFIRM_RESERVATION',
    entity: 'Reservasi RM-1002',
    timestamp: '2026-08-22T08:16:00Z',
    details: 'Slot Meja VIP-01 terkunci dan tiket dikonfirmasi otomatis setelah verifikasi ketersediaan.',
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'aud-3',
    actor: 'Sistem Reservasi Otomatis',
    action: 'AUTO_CONFIRM_RESERVATION',
    entity: 'Reservasi RM-1003',
    timestamp: '2026-08-22T09:00:00Z',
    details: 'Slot Meja M-06 terkunci otomatis untuk 2 tamu.',
    tenantId: DEFAULT_TENANT_ID,
  },
];
