import { RestaurantProfile, Table, MenuItem, Reservation, AuditEvent } from '../types/restaurant';

export const DEFAULT_TENANT_ID = 'raso-minang-padang-01';
export const TENANT_RASO_MINANG = 'raso-minang-padang-01';
export const TENANT_KOPI_NUSANTARA = 'kopi-nusantara-cafe-02';

export interface TenantSummary {
  id: string;
  name: string;
  tagline: string;
  category: string;
  themeColor: string;
  city: string;
}
export const AVAILABLE_TENANTS: TenantSummary[] = [
  {
    id: TENANT_RASO_MINANG,
    name: 'Raso Minang',
    tagline: 'Masakan Padang Autentik & Hangat di Setiap Meja',
    category: 'Restoran Minang Tradisional',
    themeColor: '#8f1d20',
    city: 'Jakarta Selatan',
  },
  {
    id: TENANT_KOPI_NUSANTARA,
    name: 'Kopi Nusantara Cafe',
    tagline: 'Artisan Coffee Roastery & Modern Eatery',
    category: 'Specialty Coffee & Bistro',
    themeColor: '#4a2c1d',
    city: 'Jakarta Selatan',
  },
];

export const initialRestaurantProfile: RestaurantProfile = {
  tenantId: DEFAULT_TENANT_ID,
  name: 'Raso Minang',
  tagline: 'Masakan Padang Autentik & Hangat di Setiap Meja',
  address: 'Jl. Rasa Nusantara No. 8, Kebayoran Baru',
  city: 'Jakarta Selatan',
  phone: '+62 812-3456-7890',
  openingHours: 'Setiap Hari: 10:00 – 22:00 WIB',
  openTime: '10:00',
  closeTime: '22:00',
  description: 'Menyajikan hidangan Minang otentik dengan racikan rempah warisan leluhur. Tersedia area Indoor ber-AC, VIP room privat, dan Outdoor teras yang asri.',
  policies: [
    'Reservasi meja diproses dengan status pending dan menunggu konfirmasi staff.',
    'Batas waktu toleransi kedatangan adalah 15 menit dari jadwal reservasi.',
    'Pembatalan atau perubahan jadwal dapat dilakukan maksimal 1 jam sebelum waktu kedatangan.',
    'Kapasitas maksimum per meja disesuaikan demi kenyamanan bersantap.'
  ]
};

export const initialTables: Table[] = [
  { id: 'tbl-1', number: 'M-01', capacity: 2, area: 'Indoor', status: 'available', tenantId: DEFAULT_TENANT_ID },
  { id: 'tbl-2', number: 'M-02', capacity: 2, area: 'Indoor', status: 'available', tenantId: DEFAULT_TENANT_ID },
  { id: 'tbl-3', number: 'M-03', capacity: 4, area: 'Indoor', status: 'available', tenantId: DEFAULT_TENANT_ID },
  { id: 'tbl-4', number: 'M-04', capacity: 4, area: 'Indoor', status: 'available', tenantId: DEFAULT_TENANT_ID },
  { id: 'tbl-5', number: 'M-05', capacity: 6, area: 'Indoor', status: 'available', tenantId: DEFAULT_TENANT_ID },
  { id: 'tbl-6', number: 'M-06', capacity: 4, area: 'Outdoor', status: 'available', tenantId: DEFAULT_TENANT_ID },
  { id: 'tbl-7', number: 'M-07', capacity: 4, area: 'Outdoor', status: 'available', tenantId: DEFAULT_TENANT_ID },
  { id: 'tbl-8', number: 'M-08', capacity: 6, area: 'Outdoor', status: 'available', tenantId: DEFAULT_TENANT_ID },
  { id: 'tbl-9', number: 'VIP-01', capacity: 8, area: 'VIP', status: 'available', tenantId: DEFAULT_TENANT_ID },
  { id: 'tbl-10', number: 'VIP-02', capacity: 10, area: 'VIP', status: 'available', tenantId: DEFAULT_TENANT_ID },
];

export const initialMenuItems: MenuItem[] = [
  // Lauk Utama
  {
    id: 'menu-1',
    name: 'Rendang Daging Sapi',
    category: 'Lauk Utama',
    price: 35000,
    description: 'Daging sapi pilihan dimasak perlahan 8 jam dengan santan kental dan 16 rempah Minang pilihan.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 2,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-2',
    name: 'Ayam Pop Spesial',
    category: 'Lauk Utama',
    price: 28000,
    description: 'Ayam kampung muda gurih lembut direbus air kelapa, disajikan dengan sambal tomat pop khas Bukittinggi.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 1,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-3',
    name: 'Dendeng Balado Batokok',
    category: 'Lauk Utama',
    price: 38000,
    description: 'Dendeng sapi renyah gurih dipukul pipih dan dilumuri cabai merah ulek kasar minyak kelapa.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 3,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-4',
    name: 'Gulai Tunjang (Kikil)',
    category: 'Lauk Utama',
    price: 36000,
    description: 'Kikil sapi empuk dan kenyal dalam kuah gulai kuning gurih kaya kapulaga dan kunyit.',
    isAvailable: true,
    isPopular: false,
    spicinessLevel: 2,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-5',
    name: 'Gulai Kepala Ikan Kakap',
    category: 'Lauk Utama',
    price: 65000,
    description: 'Kepala kakap merah segar dengan kuah gulai pedas asam beraroma daun ruku-ruku.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 2,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-6',
    name: 'Ayam Bakar Padang',
    category: 'Lauk Utama',
    price: 28000,
    description: 'Ayam berbalut bumbu kuning rempah dibakar harum arang batok kelapa.',
    isAvailable: true,
    isPopular: false,
    spicinessLevel: 2,
    tenantId: DEFAULT_TENANT_ID,
  },

  // Sayur & Kuah
  {
    id: 'menu-7',
    name: 'Sayur Daun Singkong & Nangka',
    category: 'Sayur & Kuah',
    price: 12000,
    description: 'Rebusan daun singkong segar berpadu gulai nangka muda gurih santan sedang.',
    isAvailable: true,
    isPopular: false,
    spicinessLevel: 1,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-8',
    name: 'Gulai Daun Pakis (Paku)',
    category: 'Sayur & Kuah',
    price: 15000,
    description: 'Pucuk paku segar dimasak gulai santan kunyit wangi asam kandis.',
    isAvailable: true,
    isPopular: false,
    spicinessLevel: 1,
    tenantId: DEFAULT_TENANT_ID,
  },

  // Pelengkap & Sambal
  {
    id: 'menu-9',
    name: 'Sambal Ijo Khas Padang',
    category: 'Pelengkap & Sambal',
    price: 8000,
    description: 'Cabai hijau keriting kukus ulek kasar dengan tomat hijau, bawang merah, dan perasan jeruk limau.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 2,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-10',
    name: 'Kerupuk Jangek (Kulit) Kuah Gulai',
    category: 'Pelengkap & Sambal',
    price: 12000,
    description: 'Kerupuk kulit sapi renyah disiram kuah gulai panas gurih.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 1,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-11',
    name: 'Perkedel Kentang Minang',
    category: 'Pelengkap & Sambal',
    price: 9000,
    description: 'Perkedel kentang lembut padat dengan cincangan daging sapi dan seledri.',
    isAvailable: true,
    isPopular: false,
    spicinessLevel: 1,
    tenantId: DEFAULT_TENANT_ID,
  },

  // Minuman
  {
    id: 'menu-12',
    name: 'Teh Talua (Teh Telur)',
    category: 'Minuman',
    price: 18000,
    description: 'Minuman penambah stamina khas Minang: kocokan kuning telur bebek, gula aren, seduhan teh pekat dan jeruk nipis.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 1,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-13',
    name: 'Es Tebak Tradisional',
    category: 'Minuman',
    price: 20000,
    description: 'Es campur Minang dengan olahan tepung beras tebak, cincau hitam, tapai ketan hitam, sirup merah dan santan.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 1,
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'menu-14',
    name: 'Es Timun Serut Jeruk Nipis',
    category: 'Minuman',
    price: 15000,
    description: 'Minuman penyegar peredam pedas dari serutan mentimun segar, selasih, gula asli, dan perasan jeruk nipis.',
    isAvailable: true,
    isPopular: false,
    spicinessLevel: 1,
    tenantId: DEFAULT_TENANT_ID,
  },
];

export const initialReservations: Reservation[] = [
  {
    id: 'res-1',
    code: 'RM-1001',
    customerName: 'Ahmad Fauzi',
    customerPhone: '081298765432',
    tableId: 'tbl-3',
    tableNumber: 'M-03',
    tableArea: 'Indoor',
    date: '2026-08-22',
    time: '12:30',
    guestCount: 4,
    status: 'seated',
    autoConfirmed: true,
    qrToken: 'QR-RM-1001-VERIFIED',
    seatedAt: '2026-08-22T12:28:00Z',
    paymentStatus: 'settlement',
    paymentAmount: 50000,
    paymentMethod: 'gopay',
    notes: 'Mohon siapkan sambal ijo porsi ekstra.',
    tenantId: DEFAULT_TENANT_ID,
    createdAt: '2026-08-22T10:20:00Z',
    updatedAt: '2026-08-22T12:28:00Z',
  },
  {
    id: 'res-2',
    code: 'RM-1002',
    customerName: 'Siti Rahmawati',
    customerPhone: '081388776655',
    tableId: 'tbl-9',
    tableNumber: 'VIP-01',
    tableArea: 'VIP',
    date: '2026-08-22',
    time: '19:00',
    guestCount: 8,
    status: 'confirmed',
    autoConfirmed: true,
    qrToken: 'QR-RM-1002-VERIFIED',
    paymentStatus: 'settlement',
    paymentAmount: 100000,
    paymentMethod: 'qris',
    notes: 'Makan malam keluarga besar perayaan ulang tahun.',
    tenantId: DEFAULT_TENANT_ID,
    createdAt: '2026-08-22T08:15:00Z',
    updatedAt: '2026-08-22T08:16:00Z',
  },
  {
    id: 'res-3',
    code: 'RM-1003',
    customerName: 'Budi Santoso',
    customerPhone: '085612349876',
    tableId: 'tbl-6',
    tableNumber: 'M-06',
    tableArea: 'Outdoor',
    date: '2026-08-22',
    time: '13:00',
    guestCount: 2,
    status: 'confirmed',
    autoConfirmed: true,
    qrToken: 'QR-RM-1003-VERIFIED',
    paymentStatus: 'unpaid',
    paymentAmount: 25000,
    notes: 'Area bebas asap rokok jika memungkinkan.',
    tenantId: DEFAULT_TENANT_ID,
    createdAt: '2026-08-22T09:00:00Z',
    updatedAt: '2026-08-22T09:00:00Z',
  },
  {
    id: 'res-4',
    code: 'RM-1004',
    customerName: 'Dewi Lestari',
    customerPhone: '081700112233',
    tableId: 'tbl-1',
    tableNumber: 'M-01',
    tableArea: 'Indoor',
    date: '2026-08-22',
    time: '11:00',
    guestCount: 2,
    status: 'completed',
    autoConfirmed: true,
    qrToken: 'QR-RM-1004-VERIFIED',
    seatedAt: '2026-08-22T11:02:00Z',
    completedAt: '2026-08-22T12:15:00Z',
    paymentStatus: 'settlement',
    paymentAmount: 25000,
    paymentMethod: 'bca_va',
    tenantId: DEFAULT_TENANT_ID,
    createdAt: '2026-08-22T07:00:00Z',
    updatedAt: '2026-08-22T12:15:00Z',
  },
];

export const initialAuditEvents: AuditEvent[] = [
  {
    id: 'aud-1',
    actor: 'Staf Penerima Tamu',
    action: 'GUEST_CHECKIN_SEATED',
    entity: 'Reservasi RM-1001',
    timestamp: '2026-08-22T12:28:00Z',
    details: 'Tamu Ahmad Fauzi tiba di restoran. Meja M-03 diubah ke status TERISI (Seated).',
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'aud-2',
    actor: 'Sistem Reservasi Otomatis',
    action: 'AUTO_CONFIRM_RESERVATION',
    entity: 'Reservasi RM-1002',
    timestamp: '2026-08-22T08:16:00Z',
    details: 'Slot Meja VIP-01 terkunci dan tiket dikonfirmasi otomatis setelah verifikasi ketersediaan.',
    tenantId: DEFAULT_TENANT_ID,
  },
  {
    id: 'aud-3',
    actor: 'Sistem Reservasi Otomatis',
    action: 'AUTO_CONFIRM_RESERVATION',
    entity: 'Reservasi RM-1003',
    timestamp: '2026-08-22T09:00:00Z',
    details: 'Slot Meja M-06 terkunci otomatis untuk 2 tamu.',
    tenantId: DEFAULT_TENANT_ID,
  },
];

// ==========================================
// TENANT B: KOPI NUSANTARA ARTISAN CAFE
// ==========================================
export const kopiNusantaraProfile: RestaurantProfile = {
  tenantId: TENANT_KOPI_NUSANTARA,
  name: 'Kopi Nusantara Cafe',
  tagline: 'Artisan Coffee Roastery & Modern Eatery',
  address: 'Jl. Senopati Raya No. 42, Kebayoran Baru',
  city: 'Jakarta Selatan',
  phone: '+62 821-8899-0011',
  openingHours: 'Setiap Hari: 08:00 – 23:00 WIB',
  openTime: '08:00',
  closeTime: '23:00',
  description: 'Ruang santai modern dengan sajian biji kopi Nusantara single origin (Gayo, Toraja, Kintamani) dipadukan hidangan artisan pastry, pasta, dan comfort food.',
  policies: [
    'Batas waktu reservasi meja kopi 2 jam saat jam sibuk (peak hour: 12.00-14.00 & 18.00-21.00).',
    'Area indoor non-smoking ber-AC dengan Wi-Fi 100Mbps dan colokan di setiap meja.',
    'Area outdoor garden teras ramah hewan peliharaan (pet-friendly) dan smoking area.',
    'Toleransi keterlambatan maksimal 15 menit sebelum slot dialihkan ke antrean walk-in.'
  ]
};

export const kopiNusantaraTables: Table[] = [
  { id: 'kn-tbl-1', number: 'K-01', capacity: 2, area: 'Indoor', status: 'available', tenantId: TENANT_KOPI_NUSANTARA },
  { id: 'kn-tbl-2', number: 'K-02', capacity: 2, area: 'Indoor', status: 'available', tenantId: TENANT_KOPI_NUSANTARA },
  { id: 'kn-tbl-3', number: 'K-03', capacity: 2, area: 'Indoor', status: 'available', tenantId: TENANT_KOPI_NUSANTARA },
  { id: 'kn-tbl-4', number: 'K-04', capacity: 4, area: 'Indoor', status: 'available', tenantId: TENANT_KOPI_NUSANTARA },
  { id: 'kn-tbl-5', number: 'K-05', capacity: 4, area: 'Indoor', status: 'occupied', tenantId: TENANT_KOPI_NUSANTARA },
  { id: 'kn-tbl-6', number: 'K-06', capacity: 4, area: 'Outdoor', status: 'available', tenantId: TENANT_KOPI_NUSANTARA },
  { id: 'kn-tbl-7', number: 'K-07', capacity: 4, area: 'Outdoor', status: 'occupied', tenantId: TENANT_KOPI_NUSANTARA },
  { id: 'kn-tbl-8', number: 'K-08', capacity: 6, area: 'Outdoor', status: 'available', tenantId: TENANT_KOPI_NUSANTARA },
  { id: 'kn-tbl-9', number: 'VIP-KN', capacity: 8, area: 'VIP', status: 'available', tenantId: TENANT_KOPI_NUSANTARA },
];

export const kopiNusantaraMenuItems: MenuItem[] = [
  // Minuman (Coffee & Non-Coffee)
  {
    id: 'kn-menu-1',
    name: 'Single Origin V60 Pour Over (Aceh Gayo)',
    category: 'Minuman',
    price: 35000,
    description: 'Seduhan manual biji Arabika Aceh Gayo dengan aroma floral, keasaman sitrus segar, dan aftertaste karamel manis.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 1,
    tenantId: TENANT_KOPI_NUSANTARA,
  },
  {
    id: 'kn-menu-2',
    name: 'Kopi Susu Senopati Gula Aren',
    category: 'Minuman',
    price: 28000,
    description: 'Espresso blend house specialty, susu segar creamy, dan sirup gula aren organik Garut.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 1,
    tenantId: TENANT_KOPI_NUSANTARA,
  },
  {
    id: 'kn-menu-3',
    name: 'Kyoto Drip Slow Cold Brew',
    category: 'Minuman',
    price: 38000,
    description: 'Ekstraksi dingin tetes demi tetes selama 12 jam menghasilkan cita rasa pekat, halus, dan rendah asam.',
    isAvailable: true,
    isPopular: false,
    spicinessLevel: 1,
    tenantId: TENANT_KOPI_NUSANTARA,
  },
  {
    id: 'kn-menu-4',
    name: 'Matcha Latte Uji Kyoto',
    category: 'Minuman',
    price: 34000,
    description: 'Bubuk ceremonial grade matcha asli Jepang berpadu susu creamy lembut dengan latte art.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 1,
    tenantId: TENANT_KOPI_NUSANTARA,
  },

  // Makanan Utama (Lauk Utama)
  {
    id: 'kn-menu-5',
    name: 'Nusantara Wagyu Fried Rice',
    category: 'Lauk Utama',
    price: 55000,
    description: 'Nasi goreng racikan kecap manis aromatik dengan irisan daging wagyu juicy, telur mata sapi, dan acar segar.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 2,
    tenantId: TENANT_KOPI_NUSANTARA,
  },
  {
    id: 'kn-menu-6',
    name: 'Creamy Truffle Fettuccine',
    category: 'Lauk Utama',
    price: 58000,
    description: 'Pasta fettuccine al dente dalam saus krim parmesan harum minyak truffle putih dan jamur champignon.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 1,
    tenantId: TENANT_KOPI_NUSANTARA,
  },
  {
    id: 'kn-menu-7',
    name: 'Smoked Beef Croissant Sandwich',
    category: 'Lauk Utama',
    price: 45000,
    description: 'Croissant renyah berlapis butter dengan isian daging asap premium, keju cheddar leleh, selada romaine, dan saus honey mustard.',
    isAvailable: true,
    isPopular: false,
    spicinessLevel: 1,
    tenantId: TENANT_KOPI_NUSANTARA,
  },

  // Snack & Pastry (Pelengkap & Sambal)
  {
    id: 'kn-menu-8',
    name: 'Classic French Butter Croissant',
    category: 'Pelengkap & Sambal',
    price: 25000,
    description: 'Pastry khas Prancis dipanggang renyah keemasan dengan lapisan mentega Prancis wangi dan gurih.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 1,
    tenantId: TENANT_KOPI_NUSANTARA,
  },
  {
    id: 'kn-menu-9',
    name: 'Crispy Truffle Parmesan Fries',
    category: 'Pelengkap & Sambal',
    price: 32000,
    description: 'Kentang goreng renyah bertabur keju parmesan parut dan aroma minyak truffle gurih nikmat.',
    isAvailable: true,
    isPopular: true,
    spicinessLevel: 1,
    tenantId: TENANT_KOPI_NUSANTARA,
  },
  {
    id: 'kn-menu-10',
    name: 'Cireng Krispi Sambal Rujak Aren',
    category: 'Pelengkap & Sambal',
    price: 24000,
    description: 'Camilan aci goreng renyah di luar kenyal di dalam dengan cocolan sambal rujak manis asam pedas.',
    isAvailable: true,
    isPopular: false,
    spicinessLevel: 2,
    tenantId: TENANT_KOPI_NUSANTARA,
  },

  // Sayur & Kuah (Soup & Healthy)
  {
    id: 'kn-menu-11',
    name: 'Classic Caesar Salad with Grilled Chicken',
    category: 'Sayur & Kuah',
    price: 42000,
    description: 'Selada romaine segar, potongan ayam panggang herb, crouton garing, telur rebus, dan dressing caesar gurih.',
    isAvailable: true,
    isPopular: false,
    spicinessLevel: 1,
    tenantId: TENANT_KOPI_NUSANTARA,
  },
  {
    id: 'kn-menu-12',
    name: 'Creamy Wild Mushroom Soup & Garlic Toast',
    category: 'Sayur & Kuah',
    price: 38000,
    description: 'Sup krim kental dari 3 jenis jamur hutan gurih disajikan dengan roti panggang bawang putih hangat.',
    isAvailable: true,
    isPopular: false,
    spicinessLevel: 1,
    tenantId: TENANT_KOPI_NUSANTARA,
  },
];

export const kopiNusantaraReservations: Reservation[] = [
  {
    id: 'kn-res-1',
    code: 'KN-2001',
    customerName: 'Dimas Prasetyo',
    customerPhone: '081211223344',
    tableId: 'kn-tbl-5',
    tableNumber: 'K-05',
    tableArea: 'Indoor',
    date: '2026-08-22',
    time: '14:00',
    guestCount: 4,
    status: 'seated',
    autoConfirmed: true,
    qrToken: 'QR-KN-2001-VERIFIED',
    seatedAt: '2026-08-22T14:05:00Z',
    paymentStatus: 'settlement',
    paymentAmount: 150000,
    paymentMethod: 'qris',
    notes: 'Diskusi kerja santai, butuh meja dekat colokan laptop.',
    orderItems: [
      { menuItemId: 'kn-menu-1', name: 'Single Origin V60 Pour Over (Aceh Gayo)', price: 35000, quantity: 2 },
      { menuItemId: 'kn-menu-6', name: 'Creamy Truffle Fettuccine', price: 58000, quantity: 1 },
      { menuItemId: 'kn-menu-8', name: 'Classic French Butter Croissant', price: 25000, quantity: 1 },
    ],
    orderTotal: 153000,
    tenantId: TENANT_KOPI_NUSANTARA,
    createdAt: '2026-08-22T11:00:00Z',
    updatedAt: '2026-08-22T14:05:00Z',
  },
  {
    id: 'kn-res-2',
    code: 'KN-2002',
    customerName: 'Jessica Tan',
    customerPhone: '081399887766',
    tableId: 'kn-tbl-7',
    tableNumber: 'K-07',
    tableArea: 'Outdoor',
    date: '2026-08-22',
    time: '16:30',
    guestCount: 2,
    status: 'seated',
    autoConfirmed: true,
    qrToken: 'QR-KN-2002-VERIFIED',
    seatedAt: '2026-08-22T16:35:00Z',
    paymentStatus: 'unpaid',
    paymentAmount: 70000,
    notes: 'Bawa anjing kecil (area outdoor ramah peliharaan).',
    orderItems: [
      { menuItemId: 'kn-menu-2', name: 'Kopi Susu Senopati Gula Aren', price: 28000, quantity: 1 },
      { menuItemId: 'kn-menu-4', name: 'Matcha Latte Uji Kyoto', price: 34000, quantity: 1 },
    ],
    orderTotal: 62000,
    tenantId: TENANT_KOPI_NUSANTARA,
    createdAt: '2026-08-22T13:10:00Z',
    updatedAt: '2026-08-22T16:35:00Z',
  },
];

export const kopiNusantaraAuditEvents: AuditEvent[] = [
  {
    id: 'kn-aud-1',
    actor: 'Barista / Kasir Cafe',
    action: 'GUEST_CHECKIN_SEATED',
    entity: 'Reservasi KN-2001',
    timestamp: '2026-08-22T14:05:00Z',
    details: 'Tamu Dimas Prasetyo check-in di Meja K-05. Pesanan kopi V60 & Fettuccine dicatat di POS.',
    tenantId: TENANT_KOPI_NUSANTARA,
  },
  {
    id: 'kn-aud-2',
    actor: 'Sistem Reservasi Otomatis',
    action: 'AUTO_CONFIRM_RESERVATION',
    entity: 'Reservasi KN-2002',
    timestamp: '2026-08-22T13:10:00Z',
    details: 'Slot Meja K-07 (Outdoor) terkunci untuk Jessica Tan (2 Tamu).',
    tenantId: TENANT_KOPI_NUSANTARA,
  },
];

/**
 * Helper to get initial tenant bundle
 */
export function getTenantInitialData(tenantId: string) {
  if (tenantId === TENANT_KOPI_NUSANTARA) {
    return {
      profile: kopiNusantaraProfile,
      tables: kopiNusantaraTables,
      menu: kopiNusantaraMenuItems,
      reservations: kopiNusantaraReservations,
      auditEvents: kopiNusantaraAuditEvents,
    };
  }

  return {
    profile: initialRestaurantProfile,
    tables: initialTables,
    menu: initialMenuItems,
    reservations: initialReservations,
    auditEvents: initialAuditEvents,
  };
}
